#!/usr/bin/env bash
# Install and configure HAProxy on lb-01
# Requirements:
# - Send traffic to web-01 and web-02
# - Use roundrobin algorithm
# - Manage HAProxy via init script
# - Servers must have hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02
set -e
set -o pipefail

# Update system and install HAProxy
sudo apt-get update -y
sudo systemctl stop nginx

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
# Global settings

global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
	tune.ssl.default-dh-param 4096

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend www-https
        bind *:443 ssl crt /etc/haproxy/certs/www.rentivunwa250.tech.pem
        http-request set-header X-Forwarded-Proto https
        default_backend web-servers

backend web-servers
        balance roundrobin
        server web-01 44.211.160.158:80 check
        server web-02 18.233.224.78:80 check
EOF

# Restart HAProxy to apply changes
sudo service haproxy restart
sudo systemctl stop nginx
sudo systemctl disable nginx
